const projects = [
  {
    id: '1',
    title: 'Core-working Space',
    imagePath: 'assets/img/projects/core-working.jpg',
    github: 'https://beenai.com.ng/services/',
    demo: 'https://beenai.com.ng/services/',
    node: 'https://beenai.com.ng/services/',
    react: 'https://beenai.com.ng/services/',
    express: 'https://beenai.com.ng/services/',
  },
  {
    id: '2',
    title: 'Core-working Space',
    imagePath: 'assets/img/projects/hosting-page.png',
    github: 'https://beenai.com.ng/services/',
    demo: 'https://beenai.com.ng/services/',
    node: 'https://beenai.com.ng/services/',
    react: 'https://beenai.com.ng/services/',
    express: 'https://beenai.com.ng/services/',
  },
  {
    id: '3',
    title: 'Core-working Space',
    imagePath: 'assets/img/projects/ecommerece.png',
    github: 'https://beenai.com.ng/services/',
    demo: 'https://beenai.com.ng/services/',
    node: 'https://beenai.com.ng/services/',
    react: 'https://beenai.com.ng/services/',
    express: 'https://beenai.com.ng/services/',
  },
  {
    id: '4',
    title: 'Core-working Space',
    imagePath: 'assets/img/projects/core-working.jpg',
    github: 'https://beenai.com.ng/services/',
    demo: 'https://beenai.com.ng/services/',
    node: 'https://beenai.com.ng/services/',
    react: 'https://beenai.com.ng/services/',
    express: 'https://beenai.com.ng/services/',
  },
  {
    id: '5',
    title: 'Core-working Space',
    imagePath: 'assets/img/projects/core-working.jpg',
    github: 'https://beenai.com.ng/services/',
    demo: 'https://beenai.com.ng/services/',
    node: 'https://beenai.com.ng/services/',
    react: 'https://beenai.com.ng/services/',
    express: 'https://beenai.com.ng/services/',
  },
];

module.exports = projects;
